export const adminConstants = {
    GET_ALL_STATIONS_REQUEST: 'ADMIN_GET_ALL_STATIONS_REQUEST',
    GET_ALL_STATIONS_SUCCESS: 'ADMIN_GET_ALL_STATIONS_SUCCESS',
    GET_ALL_STATIONS_FAILURE: 'ADMIN_GET_ALL_STATIONS_FAILURE',
  }
  