export const establishmentConstants = {
  LOGIN_REQUEST: 'ESTABLISHMENT_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'ESTABLISHMENT_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'ESTABLISHMENT_LOGIN_FAILURE',
  STAFF_LOGIN_REQUEST: 'STAFF_LOGIN_REQUEST',
  STAFF_LOGIN_SUCCESS: 'STAFF_LOGIN_SUCCESS',
  STAFF_LOGIN_FAILURE: 'STAFF_LOGIN_FAILURE',
  LOGOUT: 'ESTABLISHMENT_LOGOUT'
}
