export const menuConstants = {
  ORDER_DISH: 'MENU_ORDER_DISH',
  GET_ALL_DISHES_REQUEST: 'MENU_GET_ALL_DISHES_REQUEST',
  GET_ALL_DISHES_SUCCESS: 'MENU_GET_ALL_DISHES_SUCCESS',
  GET_ALL_DISHES_FAILURE: 'MENU_GET_ALL_DISHES_FAILURE',
  GET_ALL_CATEGORIES_REQUEST: 'MENU_GET_ALL_CATEGORIES_REQUEST',
  GET_ALL_CATEGORIES_SUCCESS: 'MENU_GET_ALL_CATEGORIES_SUCCESS',
  GET_ALL_CATEGORIES_FAILURE: 'MENU_GET_ALL_CATEGORIES_FAILURE',
}
