export const orderConstants = {
  POST_ORDER_REQUEST: 'ORDER_POST_ORDER_REQUEST',
  POST_ORDER_SUCCESS: 'ORDER_POST_ORDER_SUCCESS',
  POST_ORDER_FAILURE: 'ORDER_POST_ORDER_FAILURE',
  GET_ORDERS_PER_TABLE_REQUEST: 'ORDER_GET_ORDERS_PER_TABLE_REQUEST',
  GET_ORDERS_PER_TABLE_SUCCESS: 'ORDER_GET_ORDERS_PER_TABLE_SUCCESS',
  GET_ORDERS_PER_TABLE_FAILURE: 'ORDER_GET_ORDERS_PER_TABLE_FAILURE'
}
