export const orderConstants = {
  POST_ORDER_REQUEST: 'ORDER_POST_ORDER_REQUEST',
  POST_ORDER_SUCCESS: 'ORDER_POST_ORDER_SUCCESS',
  POST_ORDER_FAILURE: 'ORDER_POST_ORDER_FAILURE',
  GET_ORDERS_PER_TABLE_REQUEST: 'ORDER_GET_ORDERS_PER_TABLE_REQUEST',
  GET_ORDERS_PER_TABLE_SUCCESS: 'ORDER_GET_ORDERS_PER_TABLE_SUCCESS',
  GET_ORDERS_PER_TABLE_FAILURE: 'ORDER_GET_ORDERS_PER_TABLE_FAILURE',
  GET_BILL_PER_CUSTOMER_REQUEST: 'ORDER_GET_BILL_PER_CUSTOMER_REQUEST',
  GET_BILL_PER_CUSTOMER_SUCCESS: 'ORDER_GET_BILL_PER_CUSTOMER_SUCCESS',
  GET_BILL_PER_CUSTOMER_FAILURE: 'ORDER_GET_BILL_PER_CUSTOMER_FAILURE',
  CHANGE_ORDER_ITEM_STATUS_REQUEST: 'ORDER_CHANGE_ORDER_ITEM_STATUS_REQUEST',
  CHANGE_ORDER_ITEM_STATUS_SUCCESS: 'ORDER_CHANGE_ORDER_ITEM_STATUS_SUCCESS',
  CHANGE_ORDER_ITEM_STATUS_FAILURE: 'ORDER_CHANGE_ORDER_ITEM_STATUS_FAILURE',

}
