export const sessionInformationConstants = {
    GET_TABLE_NUMBER_REQUEST: 'SESSIONINFORMATION_GET_TABLE_NUMBER_REQUEST',
    GET_TABLE_NUMBER_SUCCESS: 'SESSIONINFORMATION_GET_TABLE_NUMBER_SUCCESS',
    GET_TABLE_NUMBER_FAILURE: 'SESSIONINFORMATION_GET_TABLE_NUMBER_FAILURE',
    GET_BILL_NUMBER_REQUEST: 'SESSIONINFORMATION_GET_BILL_NUMBER_REQUEST',
    GET_BILL_NUMBER_SUCCESS: 'SESSIONINFORMATION_GET_BILL_NUMBER_SUCCESS',
    GET_BILL_NUMBER_FAILURE: 'SESSIONINFORMATION_GET_BILL_NUMBER_FAILURE',
  }
  