export const staffConstants = {
  GET_ALL_ORDERS_REQUEST: 'STAFF_GET_ALL_ORDERS_REQUEST',
  GET_ALL_ORDERS_SUCCESS: 'STAFF_GET_ALL_ORDERS_SUCCESS',
  GET_ALL_ORDERS_FAILURE: 'STAFF_GET_ALL_ORDERS_FAILURE',
  GET_ALL_MESSAGES_REQUEST: 'STAFF_GET_ALL_MESSAGES_REQUEST',
  GET_ALL_MESSAGES_SUCCESS: 'STAFF_GET_ALL_MESSAGES_SUCCESS',
  GET_ALL_MESSAGES_FAILURE: 'STAFF_GET_ALL_MESSAGES_FAILURE',
  GET_ALL_TABLES_REQUEST: 'STAFF_GET_ALL_TABLES_REQUEST',
  GET_ALL_TABLES_SUCCESS: 'STAFF_GET_ALL_TABLES_SUCCESS',
  GET_ALL_TABLES_FAILURE: 'STAFF_GET_ALL_TABLES_FAILURE',
  UPDATE_TABLE_CALL_STATUS_REQUEST: 'STAFF_UPDATE_TABLE_CALL_STATUS_REQUEST',
  UPDATE_TABLE_CALL_STATUS_SUCCESS: 'STAFF_UPDATE_TABLE_CALL_STATUS_SUCCESS',
  UPDATE_TABLE_CALL_STATUS_FAILURE: 'STAFF_UPDATE_TABLE_CALL_STATUS_FAILURE' 
}
