export const staffConstants = {
  GET_ALL_ORDERS_REQUEST: 'STAFF_GET_ALL_ORDERS_REQUEST',
  GET_ALL_ORDERS_SUCCESS: 'STAFF_GET_ALL_ORDERS_SUCCESS',
  GET_ALL_ORDERS_FAILURE: 'STAFF_GET_ALL_ORDERS_FAILURE',
  GET_ALL_MESSAGES_REQUEST: 'STAFF_GET_ALL_MESSAGES_REQUEST',
  GET_ALL_MESSAGES_SUCCESS: 'STAFF_GET_ALL_MESSAGES_SUCCESS',
  GET_ALL_MESSAGES_FAILURE: 'STAFF_GET_ALL_MESSAGES_FAILURE',
  GET_ALL_TABLES_REQUEST: 'STAFF_GET_ALL_TABLES_REQUEST',
  GET_ALL_TABLES_SUCCESS: 'STAFF_GET_ALL_TABLES_SUCCESS',
  GET_ALL_TABLES_FAILURE: 'STAFF_GET_ALL_TABLES_FAILURE',
}
